spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
app:
  postgresql:
    url: 'jdbc:postgresql://localhost:5432/car_wash?autoReconnect=true&characterEncoding=UTF-8'
    user: 'postgres'
    password: 'qwe123qwe'
